/-
# MiniVertexAlgebras.Theorems.GoddardDong

Detailed analysis of Goddard's uniqueness theorem and Dong's lemma,
with proof sketches and applications.

L4: Core theorems — Goddard uniqueness, Dong lemma
L5: Proof techniques — induction on degree, OPE analysis
-/

import MiniVertexAlgebras.Core.Basic
import MiniVertexAlgebras.Core.AxiomEquivalence
import MiniVertexAlgebras.Core.FieldCalculus
import MiniVertexAlgebras.Theorems.Fundamental
import MiniVertexAlgebras.Core.AxiomCompat

namespace MiniVertexAlgebras


/-! ## Goddard's Uniqueness Theorem — Detailed Analysis

Statement: Let V be a vertex algebra, M a V-module, and F(z), G(z)
two fields on M. If:
1. F(z) and G(z) agree on the vacuum: F(z)|0> = G(z)|0>
2. F(z) and G(z) are mutually local with all vertex operators Y(a, z)

Then F(z) = G(z) as formal series.

Proof sketch (for VOAs):
- Write the difference D(z) = F(z) - G(z)
- D(z)|0> = 0 by (1)
- By locality, D(z) is local with all Y(a, z)
- Show by induction on conformal weight that D(z)v = 0 for all v

The key step: for v = a_{(-1)}|0> (creation),
D(z) a_{(-1)}|0> = [D(z), a_{(-1)}] |0> + a_{(-1)} D(z)|0>
The commutator is given by the OPE (from locality), and D(z)|0> = 0.
Then use the field condition to extend to all states.
-/

def goddardProofSketch (VA : VertexOperatorAlgebra) : Axiom :=
  Axiom.mk "goddardProof" (Formula.pred 0 [])
    "Proof uses induction on L_0 eigenvalue and the OPE from locality"

/-! ## Applications of Goddard's Uniqueness -/

/-- Uniqueness of the vertex operator for Virasoro algebra:
If L(z) is a field satisfying the Virasoro OPE with central charge c
and L(z)|0> = L_{-2}|0> + ..., then L(z) is unique. -/
def virasoroUniqueness : Axiom :=
  Axiom.mk "virasoroUniqueness" (Formula.pred 0 [])
    "The Virasoro field L(z) is uniquely determined by its OPE and action on vacuum"

/-- Uniqueness of Heisenberg field:
If b(z) is a field with b(z)b(w) ~ 1/(z-w)^2 and b(z)|0> = sum_{n<0} b_n z^{-n-1}|0>,
then b(z) is unique. -/
def heisenbergUniqueness : Axiom :=
  Axiom.mk "heisenbergUniqueness" (Formula.pred 0 [])
    "The Heisenberg field is uniquely determined by its 2-point function"

/-! ## Dong's Lemma — Detailed Analysis

Statement: Let a, b, c be three mutually local fields on a vertex algebra V.
Then for any n in Z, the field (a_{(n)} b)(z) is local with c(z).

Significance: Dong's lemma allows us to construct new vertex algebras
from old ones via the "coset construction" (commutant). Given a subalgebra
U of V, the commutant Com(U, V) is a vertex subalgebra.

Proof sketch:
- Mutually local means: (z_1 - z_2)^N [a(z_1), b(z_2)] = 0, etc.
- Use the Borcherds/Jacobi identity to express commutators involving a_{(n)}b
- The Jacobi identity bounds the pole order, giving locality
-/

def dongLemmaProofSketch : Axiom :=
  Axiom.mk "dongLemmaProof" (Formula.pred 0 [])
    "Proof uses the Jacobi identity to bound commutators involving a_{(n)}b"

/-! ## Corollary: Coset Construction

If U is a vertex subalgebra of V, then the coset (commutant)
Com(U, V) = {v in V | u_{(n)} v = 0 for all u in U, n >= 0}
is a vertex subalgebra of V. This follows from Dong's lemma. -/

def cosetConstructionTheorem : Axiom :=
  Axiom.mk "cosetConstruction" (Formula.pred 0 [])
    "Com(U,V) is a vertex subalgebra of V (follows from Dong's lemma)"

/-! ## Examples of Coset Constructions -/

/-- The Virasoro algebra can be obtained as a coset:
For the affine sl_2 VOA at level k, the coset Com(H, V_{sl_2}(k))
where H is the Heisenberg subalgebra gives the Virasoro VOA at
central charge c = 1 - 6(k+2)^2/(k+2)(k+3). This is the
GKO (Goddard-Kent-Olive) coset construction. -/
def gkoCosetConstruction : Axiom :=
  Axiom.mk "gkoCoset" (Formula.pred 0 [])
    "Virasoro VOA from coset of Heisenberg in affine sl_2 (GKO construction)"

/-- W-algebras from cosets:
The W_3 algebra at central charge c can be obtained as the coset
Com(H, V_{sl_3}(k)). More generally, W_n algebras from sl_n. -/
def wAlgebraCoset : Axiom :=
  Axiom.mk "wAlgebraCoset" (Formula.pred 0 [])
    "W-algebras arise from coset constructions (Arakawa, Frenkel-Kac)"

/-! ## Dong's Lemma for Lattice VOAs

For a lattice VOA V_L, the weight-1 subspace V_L(1) carries the structure
of a Lie algebra. Dong's lemma implies that the subalgebra generated by
V_L(1) is a conformal vertex subalgebra. -/

def latticeVOAApplication : Axiom :=
  Axiom.mk "latticeVOAApplication" (Formula.pred 0 [])
    "Dong's lemma applied to lattice VOAs gives affine Lie algebras"

/-! ## Weak Version of Goddard's Uniqueness (Provable in BasicVertexAlgebra)

A weaker version: If F(z) and G(z) are fields such that
F(z) v = G(z) v for all v in V, then F = G. This is trivial
by function extensionality. -/

theorem weak_goddard_uniqueness (VA : BasicVertexAlgebra)
    (F G : Int → VA.vec.carrier → VA.vec.carrier)
    (h : ∀ (n : Int) (v : VA.vec.carrier), F n v = G n v) :
    F = G := by
  ext n v
  exact h n v

/-! ## Register theorems -/

def goddardDongAxioms : AxiomSystem :=
  AxiomSystem.empty.addAxioms #[
    goddardProofSketch,
    virasoroUniqueness,
    heisenbergUniqueness,
    dongLemmaProofSketch,
    cosetConstructionTheorem,
    gkoCosetConstruction,
    wAlgebraCoset,
    latticeVOAApplication
  ]

#eval "Theorems.GoddardDong: Goddard uniqueness, Dong lemma detailed"
#eval "Theorems.GoddardDong: GKO coset construction, W-algebras"
#eval "Theorems.GoddardDong: 8 axioms registered, 1 proved theorem"

end MiniVertexAlgebras
