import MiniKacMoodyAlgebras
open MiniKacMoodyAlgebras

def main : IO Unit := do
  IO.println "== mini-kac-moody-algebras =="
  IO.println "Kac-Moody Algebras module"
  IO.println ""
  IO.println "Modules:"
  IO.println "  Core: Basic, Generators, RootSystem"
  IO.println "  Representation: CategoryO, VermaModules, IntegrableModules"
  IO.println "  Theorems: WeylKacFormula, DenominatorIdentity, MacdonaldIdentities"
  IO.println "  ProofMethods: Induction, Contragredient, Casimir"
  IO.println "  Examples: AffineSl2, AffineSl3, Hyperbolic"
  IO.println "  Applications: ConformalFieldTheory, ModularForms"
  IO.println "  Advanced: BorcherdsAlgebras, QuantumAffine"
  IO.println ""
  IO.println s!"A2: {gcm_A2.classify}"
  IO.println s!"A1^(1): {gcm_A1_affine.classify}"
  IO.println s!"G2: {gcm_G2.classify}"
  IO.println s!"D4: {gcm_D4.classify}"
  IO.println s!"Hyperbolic r2: {gcm_hyperbolic_r2.classify}"
  IO.println ""
  IO.println s!"A2 det=3: {gcm_A2_det_eq_3}"
  IO.println s!"A1^(1) det=0: {gcm_A1_affine_det_eq_0}"
  IO.println s!"A1^(1) affine: {gcm_A1_affine_isAffineType}"
  IO.println ""
  IO.println s!"W(A2) order: {WeylGroup.finiteOrder gcm_A2}"
  IO.println s!"W(B2) order: {WeylGroup.finiteOrder gcm_B2}"
  IO.println s!"W(G2) order: {WeylGroup.finiteOrder gcm_G2}"
  IO.println ""
  IO.println "== End =="