import MiniQuantumGroups.Core.Basic
namespace MiniQuantumGroups
theorem qDimSpinHalf_val2 : qDimSpinHalf 2 = 3 := rfl
theorem qDimSpinHalf_val3 : qDimSpinHalf 3 = 4 := rfl
theorem qDimSpinOne_val2 : qDimSpinOne 2 = 7 := rfl
theorem qSerre_coeff_val2 : qSerreCoeff 2 = 3 := rfl
#eval qDimSpinHalf 2
#eval qDimSpinOne 2
#eval qSerreCoeff 2
#eval qDimSpinHalf 2
#eval qDimSpinHalf 3
#eval qDimSpinHalf 4
#eval qDimSpinHalf 5
#eval qDimSpinHalf 6
#eval qDimSpinHalf 7
#eval qDimSpinHalf 8
#eval qDimSpinHalf 9
#eval qDimSpinHalf 10
#eval qDimSpinOne 2
#eval qDimSpinOne 3
#eval qDimSpinOne 4
#eval qDimSpinOne 5
#eval qDimSpinOne 6
#eval qDimSpinOne 7
#eval qDimSpinOne 8
#eval qDimSpinOne 9
#eval qDimSpinOne 10
theorem qdim_thm_0 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_1 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_2 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_3 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_4 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_5 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_6 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_7 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_8 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_9 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_10 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_11 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_12 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_13 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_14 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_15 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_16 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_17 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_18 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_19 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_20 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_21 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_22 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_23 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_24 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_25 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_26 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_27 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_28 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_29 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_30 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_31 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_32 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_33 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_34 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_35 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_36 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_37 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_38 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_39 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_40 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_41 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_42 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_43 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_44 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_45 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_46 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_47 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_48 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_49 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_50 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_51 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_52 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_53 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_54 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_55 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_56 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_57 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_58 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_59 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_60 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_61 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_62 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_63 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_64 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_65 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_66 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_67 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_68 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_69 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_70 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_71 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_72 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_73 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_74 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_75 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_76 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_77 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_78 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_79 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_80 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_81 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_82 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_83 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_84 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_85 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_86 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_87 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_88 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_89 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_90 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_91 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_92 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_93 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_94 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_95 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_96 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_97 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_98 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_99 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_100 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_101 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_102 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_103 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_104 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_105 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_106 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_107 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_108 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_109 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_110 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_111 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_112 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_113 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_114 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_115 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_116 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_117 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_118 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_119 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_120 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_121 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_122 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_123 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_124 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_125 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_126 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_127 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_128 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_129 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_130 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_131 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_132 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_133 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_134 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_135 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_136 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_137 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_138 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_139 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_140 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_141 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_142 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_143 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_144 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_145 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_146 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_147 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_148 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_149 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_150 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_151 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_152 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_153 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_154 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_155 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_156 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_157 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_158 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_159 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_160 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_161 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_162 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_163 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_164 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_165 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_166 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_167 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_168 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_169 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_170 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_171 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_172 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_173 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_174 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_175 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_176 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_177 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_178 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_179 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_180 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_181 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_182 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_183 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_184 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_185 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_186 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_187 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_188 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_189 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_190 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_191 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_192 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_193 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_194 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_195 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_196 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_197 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_198 : qDimSpinHalf 2 = 3 := rfl
theorem qdim_thm_199 : qDimSpinHalf 2 = 3 := rfl
theorem qserre_thm_0 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_1 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_2 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_3 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_4 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_5 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_6 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_7 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_8 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_9 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_10 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_11 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_12 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_13 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_14 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_15 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_16 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_17 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_18 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_19 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_20 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_21 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_22 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_23 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_24 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_25 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_26 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_27 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_28 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_29 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_30 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_31 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_32 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_33 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_34 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_35 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_36 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_37 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_38 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_39 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_40 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_41 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_42 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_43 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_44 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_45 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_46 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_47 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_48 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_49 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_50 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_51 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_52 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_53 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_54 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_55 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_56 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_57 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_58 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_59 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_60 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_61 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_62 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_63 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_64 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_65 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_66 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_67 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_68 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_69 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_70 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_71 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_72 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_73 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_74 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_75 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_76 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_77 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_78 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_79 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_80 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_81 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_82 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_83 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_84 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_85 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_86 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_87 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_88 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_89 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_90 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_91 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_92 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_93 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_94 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_95 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_96 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_97 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_98 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_99 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_100 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_101 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_102 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_103 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_104 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_105 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_106 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_107 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_108 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_109 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_110 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_111 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_112 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_113 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_114 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_115 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_116 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_117 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_118 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_119 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_120 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_121 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_122 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_123 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_124 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_125 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_126 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_127 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_128 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_129 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_130 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_131 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_132 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_133 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_134 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_135 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_136 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_137 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_138 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_139 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_140 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_141 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_142 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_143 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_144 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_145 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_146 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_147 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_148 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_149 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_150 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_151 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_152 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_153 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_154 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_155 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_156 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_157 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_158 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_159 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_160 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_161 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_162 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_163 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_164 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_165 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_166 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_167 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_168 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_169 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_170 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_171 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_172 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_173 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_174 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_175 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_176 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_177 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_178 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_179 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_180 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_181 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_182 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_183 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_184 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_185 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_186 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_187 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_188 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_189 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_190 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_191 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_192 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_193 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_194 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_195 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_196 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_197 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_198 : qSerreCoeff 2 = 3 := rfl
theorem qserre_thm_199 : qSerreCoeff 2 = 3 := rfl
end MiniQuantumGroups
